text=input("Enter any text =>")
print(text)
print(text.upper())
print(text.lower())
print(text.startswith("a"))
print(text.endswith("a"))
print(text.index(0,5))
print(text.count("a",0,8))
print(text.capitalize())
print(text.replace("p","t"))
